const i18n = {
    "zh-TW": {
        appTitle: "Woof Cal 汪卡管家",
        dateLabel: "📅 日期：", // ✨ 已修正：縮短文字以優化排版
        totalIntake: "今日攝取", goal: "目標", cal: "熱量",
        pro: "蛋白質", fat: "脂肪", carb: "碳水", sugar: "糖", sod: "鈉(mg)", 
        sat: "飽和脂肪", 
        trans: "反式脂肪", 
        water: "目標水",
        chartTitle: "📊 營養與熱量分析", chartMacro: "今日三大營養素 (PFC)", chartWeekly: "本週熱量趨勢",
        aiTitle: "📸 AI 飲食分析", btnPhoto: "📸 1. 拍照 / 選擇圖片", btnAnalyze: "送出分析", aiLoading: "AI 正在分析食物營養，請稍候...",
        aiDescPlaceholder: "📝 補充說明 (例如：這是一碗牛肉麵，沒加蔥)...",
        recordTitle: "飲食紀錄", 
        manualLabel: "手動補充", 
        placeholderName: "食物名稱", placeholderCal: "卡路里",
        btnAdd: "➕ 加入紀錄", btnFavSave: "加入最愛", btnFavLoad: "選擇常吃食物", btnFavAi: "加入最愛",
        settingsTitle: "⚙️ 個人數據設定", gender: "性別", male: "男", female: "女", age: "年齡", height: "身高", weight: "體重",
        activity: "活動量", act1: "久坐 (辦公室)", act2: "輕度 (每週運動1-3天)", act3: "中度 (每週運動3-5天)", act4: "高度 (每週運動6-7天)",
        mealMode: "🍽️ 每日餐數模式", mode4: "標準 (3餐+點心)", mode3: "3餐 (無點心)", mode2: "2餐 (168斷食)", mode1: "1餐 (OMAD)",
        btnCalc: "🔄 儲存並更新介面", resTdee: "TDEE", resTarget: "減重目標",
        modalTitle: "AI 分析報告", modalAsk: "請問這是哪一餐？", btnCancel: "取消",
        favTitle: "常吃食物清單", btnClose: "關閉",
        menuImport: "匯入還原", menuExport: "匯出備份", menuTheme: "切換主題", menuLang: "語言", suggest: "建議",
        langTitle: "語言", langCancel: "取消",
        meals: { breakfast: "🍳 早餐", lunch: "🍱 午餐", dinner: "🍲 晚餐", snack: "🍪 點心", meal1: "🍽️ 第一餐", meal2: "🍽️ 第二餐", mealBig: "🏆 唯一大餐" },
        alertDel: "確定要刪除？", alertFavAdded: "已加入最愛！", alertFavExist: "這個食物已經在最愛清單囉！", alertSelImg: "請先選擇圖片！", alertAiFail: "AI 分析失敗：", alertFill: "請填寫資料", alertNameCal: "請輸入名稱與熱量", alertImportOk: "🎉 資料還原成功！", alertImportFail: "❌ 檔案格式錯誤",
        weightTitle: "⚖️ 體重紀錄", weightInputPlaceholder: "今日體重 (kg)", btnSaveWeight: "儲存", weightChartTitle: "📈 體重趨勢 (近30天)", textAiLabel: "📝 請輸入您剛剛吃的食物或補充說明來提升AI準確度：", textAiPlaceholder: "例如：一碗牛肉麵，沒加蔥，還有一盤燙青菜...", appSettingsTitle: "🔧 應用程式設定", navDaily: "日記", navDashboard: "儀表板", navAi: "AI", navSettings: "設定", txtWeightSettingsTitle: "體重 (kg)", alertWeightSaved: "體重紀錄已儲存！", alertInvalidWeight: "請輸入有效的體重數值！", alertSelImgOrText: "請選擇圖片，或輸入文字描述！",
        petMsg1: "汪... 肚子好餓喔... (0%)", petMsg2: "有點力氣了，但還想再吃一點...", petMsg3: "聞到香味了，正在尋找食物！", petMsg4: "營養剛剛好，太棒了！", petMsg5: "嗝... 吃太多了啦！", petEatMsg: "阿姆阿姆... 好吃！", petInteractMsg1: "汪！你今天喝水了嗎？", petInteractMsg2: "保持健康，我們一起加油！", petInteractMsg3: "我最喜歡吃健康的食物了！", petInteractMsg4: "摸我也不會變瘦喔，去運動吧！ XD", petInteractMsg5: "記得要細嚼慢嚥喔！",
        macroGoalTitle: "📊 營養攝取建議 (估算值)：", txtTdeeUnit: " (總消耗熱量)", txtResTarget: "建議目標",
        txtTargetCalDisplayUnit: "目標",
        phPro: "蛋白質", phFat: "脂肪", phCarb: "碳水", phSugar: "糖", phSod: "鈉(mg)", phSat: "飽和脂", phTrans: "反式脂",
        txtManualLabel: "手動補充", btnAddRecord: "加入紀錄", txtRecordTitle: "飲食紀錄", 
        btnFavSave: "加入最愛", btnFavLoad: "選擇常吃食物", phFoodName: "食物名稱 (必填)", phFoodCal: "熱量 (kcal) (必填)",
        chartCalTrend: "📈 熱量攝取趨勢", chartProteinTrend: "💪 蛋白質攝取趨勢", chart7d: "7天", chart30d: "30天", chartTdeeTarget: "TDEE 目標線",
        fiber: "膳食纖維", healthScoreLabel: "🏅 健康評分", aiItemsLabel: "📋 食物成分估算", itemName: "食物", itemWeight: "重量", addItem: "＋新增成分", recalculate: "🔄 重新計算", unsavedWarning: "注意，您的營養數據尚未保存，確定要離開嗎？",
        detailTitle: "📋 詳細營養資訊", noData: "--", btnDetailClose: "關閉"
    },
    "zh-CN": {
        appTitle: "Woof Cal 汪卡管家",
        dateLabel: "📅 日期：", // ✨ 已修正
        totalIntake: "今日摄取", goal: "目标", cal: "热量",
        pro: "蛋白质", fat: "脂肪", carb: "碳水", sugar: "糖", sod: "钠(mg)", 
        sat: "饱和脂肪", 
        trans: "反式脂肪", 
        water: "目标水",
        chartTitle: "📊 营养与热量分析", chartMacro: "今日三大营养素 (PFC)", chartWeekly: "本周热量趋势",
        aiTitle: "📸 AI 饮食分析", btnPhoto: "📸 1. 拍照 / 选择图片", btnAnalyze: "送出分析", aiLoading: "AI 正在分析食物营养，请稍候...",
        aiDescPlaceholder: "📝 补充说明 (例如：这是一碗牛肉面，没加葱)...",
        recordTitle: "饮食记录", 
        manualLabel: "手动补充", 
        placeholderName: "食物名称", placeholderCal: "卡路里",
        btnAdd: "➕ 加入记录", btnFavSave: "加入收藏", btnFavLoad: "选择常吃食物", btnFavAi: "加入收藏",
        settingsTitle: "⚙️ 个人数据设定", gender: "性别", male: "男", female: "女", age: "年龄", height: "身高", weight: "体重",
        activity: "活动量", act1: "久坐 (办公室)", act2: "轻度 (每周运动1-3天)", act3: "中度 (每周运动3-5天)", act4: "高度 (每周运动6-7天)",
        mealMode: "🍽️ 每日餐数模式", mode4: "标准 (3餐+点心)", mode3: "3餐 (无点心)", mode2: "2餐 (168断食)", mode1: "1餐 (OMAD)",
        btnCalc: "🔄 保存并更新界面", resTdee: "TDEE", resTarget: "减重目标",
        modalTitle: "AI 分析报告", modalAsk: "请问这是哪一餐？", btnCancel: "取消",
        favTitle: "常吃食物清单", btnClose: "关闭",
        menuImport: "导入还原", menuExport: "导出备份", menuTheme: "切换主题", menuLang: "语言", suggest: "建议",
        langTitle: "语言", langCancel: "取消",
        meals: { breakfast: "🍳 早餐", lunch: "🍱 午餐", dinner: "🍲 晚餐", snack: "🍪 点心", meal1: "🍽️ 第一餐", meal2: "🍽️ 第二餐", mealBig: "🏆 唯一大餐" },
        alertDel: "确定要删除？", alertFavAdded: "已加入收藏！", alertFavExist: "这个食物已经在收藏清单啰！", alertSelImg: "请先选择图片！", alertAiFail: "AI 分析失败：", alertFill: "请填写资料", alertNameCal: "请输入名称与热量", alertImportOk: "🎉 资料还原成功！", alertImportFail: "❌ 档案格式错误",
        weightTitle: "⚖️ 体重记录", weightInputPlaceholder: "今日体重 (kg)", btnSaveWeight: "保存", weightChartTitle: "📈 体重趋势 (近30天)", textAiLabel: "📝 请输入您刚吃的食物或补充说明来提升AI准确度：", textAiPlaceholder: "例如：一碗牛肉面，没加葱，还有一盘烫青菜...", appSettingsTitle: "🔧 应用程序设定", navDaily: "日记", navDashboard: "面板", navAi: "AI", navSettings: "设置", txtWeightSettingsTitle: "体重 (kg)", alertWeightSaved: "体重记录已保存！", alertInvalidWeight: "请输入有效的体重数值！", alertSelImgOrText: "请选择图片，或输入文字描述！",
        petMsg1: "汪... 肚子好饿喔... (0%)", petMsg2: "有点力气了，但还想再吃一点...", petMsg3: "闻到香味了，正在寻找食物！", petMsg4: "营养刚刚好，太棒了！", petMsg5: "嗝... 吃太多了啦！", petEatMsg: "阿姆阿姆... 好吃！", petInteractMsg1: "汪！你今天喝水了吗？", petInteractMsg2: "保持健康，我们一起加油！", petInteractMsg3: "我最喜欢吃健康的食物了！", petInteractMsg4: "摸我也不会变瘦喔，去运动吧！ XD", petInteractMsg5: "记得要细嚼慢咽喔！",
        macroGoalTitle: "📊 营养摄取建议 (估算值)：", txtTdeeUnit: " (总消耗热量)", txtResTarget: "建议目标",
        txtTargetCalDisplayUnit: "目标",
        phPro: "蛋白质", phFat: "脂肪", phCarb: "碳水", phSugar: "糖", phSod: "钠(mg)", phSat: "饱和脂", phTrans: "反式脂",
        txtManualLabel: "手动补充", btnAddRecord: "加入记录", txtRecordTitle: "饮食记录", 
        btnFavSave: "加入收藏", btnFavLoad: "选择常吃食物", phFoodName: "食物名称 (必填)", phFoodCal: "热量 (kcal) (必填)",
        chartCalTrend: "📈 热量摄取趋势", chartProteinTrend: "💪 蛋白质摄取趋势", chart7d: "7天", chart30d: "30天", chartTdeeTarget: "TDEE 目标线",
        fiber: "膳食纤维", healthScoreLabel: "🏅 健康评分", aiItemsLabel: "📋 食物成分估算", itemName: "食物", itemWeight: "重量", addItem: "＋新增成分", recalculate: "🔄 重新计算", unsavedWarning: "注意，您的营养数据尚未保存，确定要离开吗？",
        detailTitle: "📋 详细营养信息", noData: "--", btnDetailClose: "关闭"
    },
    "en": {
        appTitle: "Woof Cal - AI Diet Tracker",
        dateLabel: "📅 Date:", totalIntake: "Total Intake", goal: "Goal", cal: "Calories",
        pro: "Protein", fat: "Fat", carb: "Carb", sugar: "Sugar", sod: "Sodium", 
        sat: "Sat. Fat", 
        trans: "Trans Fat", water: "Water",
        chartTitle: "📊 Nutrition Analysis", chartMacro: "Macros (PFC)", chartWeekly: "Weekly Calories",
        aiTitle: "📸 AI Analysis", btnPhoto: "📸 1. Select Photo", btnAnalyze: "Analyze", aiLoading: "AI is analyzing...",
        aiDescPlaceholder: "📝 Optional description (e.g. Beef noodles, no onions)...",
        recordTitle: "Food Log", 
        manualLabel: "Manual Entry", 
        placeholderName: "Food Name", placeholderCal: "Calories",
        btnAdd: "➕ Add Log", btnFavSave: "Save Favorite", btnFavLoad: "Load Favorite", btnFavAi: "Save to Favorites",
        settingsTitle: "⚙️ Profile Settings", gender: "Gender", male: "Male", female: "Female", age: "Age", height: "Height", weight: "Weight",
        activity: "Activity Level", act1: "Sedentary", act2: "Lightly Active", act3: "Moderately Active", act4: "Very Active",
        mealMode: "🍽️ Meal Mode", mode4: "Standard (3+Snack)", mode3: "3 Meals", mode2: "2 Meals (168)", mode1: "OMAD",
        btnCalc: "🔄 Save & Update", resTdee: "TDEE", resTarget: "Target",
        modalTitle: "AI Report", modalAsk: "Which meal is this?", btnCancel: "Cancel",
        favTitle: "Favorite Foods", btnClose: "Close",
        menuImport: "Import Data", menuExport: "Export Data", menuTheme: "Switch Theme", menuLang: "Language", suggest: "Goal",
        langTitle: "Language", langCancel: "Cancel",
        meals: { breakfast: "🍳 Breakfast", lunch: "🍱 Lunch", dinner: "🍲 Dinner", snack: "🍪 Snack", meal1: "🍽️ Meal 1", meal2: "🍽️ Meal 2", mealBig: "🏆 Big Meal" },
        alertDel: "Delete this item?", alertFavAdded: "Saved to favorites!", alertFavExist: "Already in favorites!", alertSelImg: "Select image first!", alertAiFail: "AI Failed: ", alertFill: "Fill all fields", alertNameCal: "Enter name and calories", alertImportOk: "🎉 Data Restored!", alertImportFail: "❌ Invalid File",
        weightTitle: "⚖️ Weight Record", weightInputPlaceholder: "Today's Weight (kg)", btnSaveWeight: "Save", weightChartTitle: "📈 Weight Trend (Last 30 Days)", textAiLabel: "📝 Enter the food you just ate, or add details to improve AI accuracy:", textAiPlaceholder: "e.g., Bowl of beef noodles, no onions...", appSettingsTitle: "🔧 App Settings", navDaily: "Daily", navDashboard: "Dashboard", navAi: "AI", navSettings: "Settings", txtWeightSettingsTitle: "Weight (kg)", alertWeightSaved: "Weight saved successfully!", alertInvalidWeight: "Please enter a valid weight!", alertSelImgOrText: "Please select an image or enter a description!",
        petMsg1: "Woof... So hungry... (0%)", petMsg2: "Got some energy, but want more food...", petMsg3: "Smelled food! Searching...", petMsg4: "Perfect nutrition! Great job!", petMsg5: "Burp... Ate too much!", petEatMsg: "Nom nom nom... Yummy!", petInteractMsg1: "Woof! Drank water today?", petInteractMsg2: "Let's stay healthy together!", petInteractMsg3: "I love healthy food!", petInteractMsg4: "Petting me won't make you thin, go exercise! XD", petInteractMsg5: "Remember to chew slowly!",
        macroGoalTitle: "📊 Recommended Macros (Estimated):", txtTdeeUnit: " (Total Energy Expended)", txtResTarget: "Target Goal",
        txtTargetCalDisplayUnit: "Goal",
        phPro: "Protein", phFat: "Fat", phCarb: "Carb", phSugar: "Sugar", phSod: "Sodium", phSat: "Sat. Fat", phTrans: "Trans Fat",
        txtManualLabel: "Manual Entry", btnAddRecord: "Add Record", txtRecordTitle: "Diet Record", 
        btnFavSave: "Save Favorite", btnFavLoad: "Load Favorite", phFoodName: "Food Name (Required)", phFoodCal: "Calories (kcal) (Req)",
        chartCalTrend: "📈 Calorie Intake Trend", chartProteinTrend: "💪 Protein Intake Trend", chart7d: "7D", chart30d: "30D", chartTdeeTarget: "TDEE Target",
        fiber: "Fiber", healthScoreLabel: "🏅 Health Score", aiItemsLabel: "📋 Estimated Food Items", itemName: "Item", itemWeight: "Weight", addItem: "＋ Add Item", recalculate: "🔄 Recalculate", unsavedWarning: "Warning: your nutrition data has not been saved. Are you sure you want to leave?",
        detailTitle: "📋 Nutrition Details", noData: "--", btnDetailClose: "Close"
    },
    "ja": {
        appTitle: "Woof Cal - AI Diet Tracker",
        dateLabel: "📅 日付：", totalIntake: "摂取カロリー", goal: "目標", cal: "熱量",
        pro: "タンパク質", fat: "脂質", carb: "炭水化物", sugar: "糖質", sod: "塩分", 
        sat: "飽和脂肪酸", 
        trans: "トランス脂肪", water: "水分目標",
        chartTitle: "📊 栄養分析", chartMacro: "三大栄養素 (PFC)", chartWeekly: "週間カロリー",
        aiTitle: "📸 AI食事分析", btnPhoto: "📸 1. 写真を選択", btnAnalyze: "分析開始", aiLoading: "AI分析中...",
        aiDescPlaceholder: "📝 補足説明 (例: 牛肉麺、ネギ抜き)...",
        recordTitle: "食事記録", 
        manualLabel: "手動入力", 
        placeholderName: "食品名", placeholderCal: "kcal",
        btnAdd: "➕ 記録追加", btnFavSave: "お気に入り保存", btnFavLoad: "お気に入りから選択", btnFavAi: "お気に入りに保存",
        settingsTitle: "⚙️ プロフィール設定", gender: "性別", male: "男性", female: "女性", age: "年齢", height: "身長", weight: "体重",
        activity: "活動レベル", act1: "座り仕事", act2: "軽い運動 (週1-3)", act3: "中程度の運動 (週3-5)", act4: "激しい運動 (週6-7)",
        mealMode: "🍽️ 食事回数", mode4: "標準 (3食+間食)", mode3: "3食のみ", mode2: "2食 (168断食)", mode1: "1食 (OMAD)",
        btnCalc: "🔄 保存して更新", resTdee: "TDEE", resTarget: "目標",
        modalTitle: "AI分析レポート", modalAsk: "どの食事ですか？", btnCancel: "キャンセル",
        favTitle: "お気に入りリスト", btnClose: "閉じる",
        menuImport: "復元", menuExport: "バックアップ", menuTheme: "テーマ切替", menuLang: "言語", suggest: "目安",
        langTitle: "言語", langCancel: "キャンセル",
        meals: { breakfast: "🍳 朝食", lunch: "🍱 昼食", dinner: "🍲 夕食", snack: "🍪 間食", meal1: "🍽️ 食事1", meal2: "🍽️ 食事2", mealBig: "🏆 大盛り" },
        alertDel: "削除しますか？", alertFavAdded: "お気に入りに保存しました！", alertFavExist: "既に保存されています", alertSelImg: "画像を選択してください", alertAiFail: "AIエラー: ", alertFill: "全ての項目を入力してください", alertNameCal: "名称とカロリーを入力", alertImportOk: "🎉 復元完了！", alertImportFail: "❌ ファイルエラー",
        weightTitle: "⚖️ 体重記録", weightInputPlaceholder: "今日の体重 (kg)", btnSaveWeight: "保存", weightChartTitle: "📈 体重トレンド (過去30日間)", textAiLabel: "📝 食べたものを入力するか、AI精度向上のため補足してください：", textAiPlaceholder: "例：ネギ抜きの牛肉麺...", appSettingsTitle: "🔧 アプリ設定", navDaily: "デイリー", navDashboard: "ダッシュボード", navAi: "AI", navSettings: "設定", txtWeightSettingsTitle: "体重 (kg)", alertWeightSaved: "体重が保存されました！", alertInvalidWeight: "有効な体重を入力してください！", alertSelImgOrText: "画像を選択するか、テキストを入力してください！",
        petMsg1: "ワン... お腹すいた... (0%)", petMsg2: "元気出たけど、もっと食べたい...", petMsg3: "いい匂い！ご飯探してます！", petMsg4: "栄養バッチリ！ 최고！", petMsg5: "ゲップ... 食べ過ぎた！", petEatMsg: "モグモグ... 美味しい！", petInteractMsg1: "ワン！水飲んだ？", petInteractMsg2: "一緒に健康になろう！", petInteractMsg3: "健康なご飯が大好き！", petInteractMsg4: "撫でても痩せないよ、運動しなきゃ！ XD", petInteractMsg5: "ゆっくり噛んで食べてね！",
        macroGoalTitle: "📊 栄養摂取目安 (推定：", txtTdeeUnit: " (総消費カロリー)", txtResTarget: "推奨目標",
        txtTargetCalDisplayUnit: "目標",
        phPro: "タンパク質", phFat: "脂質", phCarb: "炭水化物", phSugar: "糖質", phSod: "塩分", phSat: "飽和脂肪", phTrans: "トランス脂肪",
        txtManualLabel: "手動入力", btnAddRecord: "記録を追加", txtRecordTitle: "食事記録", 
        btnFavSave: "お気に入りに追加", btnFavLoad: "お気に入りを読み込む", phFoodName: "食べ物の名前 (必須)", phFoodCal: "カロリー (kcal) (必須)",
        chartCalTrend: "📈 カロリー摂取トレンド", chartProteinTrend: "💪 タンパク質トレンド", chart7d: "7日", chart30d: "30日", chartTdeeTarget: "TDEE 目標ライン",
        fiber: "食物繊維", healthScoreLabel: "🏅 ヘルススコア", aiItemsLabel: "📋 食材内訳の推定", itemName: "食材", itemWeight: "量", addItem: "＋食材追加", recalculate: "🔄 再計算", unsavedWarning: "注意：栄養データはまだ保存されていません。離れてもよろしいですか？",
        detailTitle: "📋 詳細栄養情報", noData: "--", btnDetailClose: "閉じる"
    },
    "ko": {
        appTitle: "Woof Cal - AI Diet Tracker",
        dateLabel: "📅 날짜:", totalIntake: "총 섭취량", goal: "목표", cal: "열량",
        pro: "단백질", fat: "지방", carb: "탄수화물", sugar: "당류", sod: "나트륨", 
        sat: "포화지방", 
        trans: "트랜스지방", water: "수분",
        chartTitle: "📊 영양 분석", chartMacro: "거시 영양소", chartWeekly: "주간 칼로리",
        aiTitle: "📸 AI 분석", btnPhoto: "📸 1. 사진 선택", btnAnalyze: "분석 시작", aiLoading: "AI 분석 중...",
        aiDescPlaceholder: "📝 추가 설명 (예: 양파 제외한 소고기 국수)...",
        recordTitle: "음식 기록", 
        manualLabel: "수동 입력", 
        placeholderName: "음식 이름", placeholderCal: "kcal",
        btnAdd: "➕ 기록 추가", btnFavSave: "즐겨찾기 저장", btnFavLoad: "즐겨찾기 로드", btnFavAi: "즐겨찾기에 저장",
        settingsTitle: "⚙️ 프로필 설정", gender: "성별", male: "남성", female: "여성", age: "나이", height: "키", weight: "체중",
        activity: "활동 수준", act1: "앉아서 생활", act2: "가벼운 활동", act3: "보통 활동", act4: "매우 활동적",
        mealMode: "🍽️ 식사 모드", mode4: "표준 (3끼+간식)", mode3: "3끼", mode2: "2끼 (168 단식)", mode1: "1끼 (1일 1식)",
        btnCalc: "🔄 저장 및 업데이트", resTdee: "TDEE", resTarget: "목표",
        modalTitle: "AI 보고서", modalAsk: "어느 식사입니까?", btnCancel: "취소",
        favTitle: "즐겨찾는 음식", btnClose: "닫기",
        menuImport: "데이터 가져오기", menuExport: "데이터 내보내기", menuTheme: "테마 변경", menuLang: "언어 선택", suggest: "권장",
        langTitle: "언어", langCancel: "취소",
        meals: { breakfast: "🍳 아침", lunch: "🍱 점심", dinner: "🍲 저녁", snack: "🍪 간식", meal1: "🍽️ 식사 1", meal2: "🍽️ 식사 2", mealBig: "🏆 큰 식사" },
        alertDel: "항목을 삭제하시겠습니까?", alertFavAdded: "즐겨찾기에 저장되었습니다!", alertFavExist: "이미 즐겨찾기에 있습니다!", alertSelImg: "먼저 이미지를 선택하세요!", alertAiFail: "AI 실패: ", alertFill: "모든 필드를 채워주세요", alertNameCal: "이름과 칼로리를 입력하세요", alertImportOk: "🎉 데이터 복원 성공!", alertImportFail: "❌ 잘못된 파일 형식",
        weightTitle: "⚖️ 체중 기록", weightInputPlaceholder: "오늘의 체중 (kg)", btnSaveWeight: "저장", weightChartTitle: "📈 체중 변화 (최근 30일)", textAiLabel: "📝 방금 먹은 음식을 입력하거나 AI 정확도를 높이기 위해 보충 설명하세요：", textAiPlaceholder: "예: 우육면, 파 빼고...", appSettingsTitle: "🔧 앱 설정", navDaily: "다이어리", navDashboard: "대시보드", navAi: "AI", navSettings: "설정", txtWeightSettingsTitle: "체중 (kg)", alertWeightSaved: "체중이 저장되었습니다!", alertInvalidWeight: "올바른 체중을 입력하세요!", alertSelImgOrText: "사진을 선택하거나 텍스트를 입력하세요!",
        petMsg1: "멍멍... 배고파... (0%)", petMsg2: "기운이 나지만 더 먹고 싶어...", petMsg3: "맛있는 냄새! 찾는 중...", petMsg4: "영양 완벽! 잘했어!", petMsg5: "꺼억... 너무 많이 먹었어!", petEatMsg: "냠냠... 맛있어!", petInteractMsg1: "멍! 오늘 물 마셨어?", petInteractMsg2: "같이 건강해지자!", petInteractMsg3: "건강한 음식이 좋아!", petInteractMsg4: "쓰다듬는다고 날씬해지진 않아, 운동해! XD", petInteractMsg5: "천천히 씹어 먹어!",
        macroGoalTitle: "📊 권장 영양소 (추정):", txtTdeeUnit: " (총 에너지 소비량)", txtResTarget: "목표 체중",
        txtTargetCalDisplayUnit: "목표",
        phPro: "단백질", phFat: "지방", phCarb: "탄수화물", phSugar: "당", phSod: "나트륨", phSat: "포화 지방", phTrans: "트랜스 지방",
        txtManualLabel: "수동 입력", btnAddRecord: "기록 추가", txtRecordTitle: "음식 기록", 
        btnFavSave: "즐겨찾기 저장", btnFavLoad: "즐겨찾기 선택", phFoodName: "음식 이름 (필수)", phFoodCal: "칼로리 (kcal) (필수)",
        chartCalTrend: "📈 칼로리 섭취 추이", chartProteinTrend: "💪 단백질 섭취 추이", chart7d: "7일", chart30d: "30일", chartTdeeTarget: "TDEE 목표선",
        fiber: "식이섬유", healthScoreLabel: "🏅 건강 점수", aiItemsLabel: "📋 추정 식재료", itemName: "식재료", itemWeight: "중량", addItem: "＋ 항목 추가", recalculate: "🔄 재계산", unsavedWarning: "주의: 영양 데이터가 저장되지 않았습니다. 나가시겠습니까?",
        detailTitle: "📋 상세 영양 정보", noData: "--", btnDetailClose: "닫기"
    },
    "ar": {
        appTitle: "Woof Cal - AI Diet Tracker",
        dateLabel: "📅 التاريخ:", totalIntake: "إجمالي السعرات", goal: "الهدف", cal: "السعرات",
        pro: "بروتين", fat: "دهون", carb: "كربوهيدرات", sugar: "سكر", sod: "صوديوم", 
        sat: "الدهون المشبعة", 
        trans: "الدهون المتحولة", water: "الماء",
        chartTitle: "📊 التحليل الغذائي", chartMacro: "الماكروز", chartWeekly: "السعرات الأسبوعية",
        aiTitle: "📸 تحليل الذكاء الاصطناعي", btnPhoto: "📸 ١. اختيار صوره", btnAnalyze: "بدء التحليل", aiLoading: "جاري تحليل الـ AI...",
        aiDescPlaceholder: "📝 وصف إضافي (مثال: حساء دجاج بدون بصل)...",
        recordTitle: "سجل الطعام", 
        manualLabel: "إدخال يدوي", 
        placeholderName: "اسم الطعام", placeholderCal: "السعرات",
        btnAdd: "➕ إضافة سجل", btnFavSave: "حفظ في المفضلة", btnFavLoad: "اختيار من المفضلة", btnFavAi: "حفظ كمفضل",
        settingsTitle: "⚙️ إعدادات الملف الشخصي", gender: "الجنس", male: "ذكر", female: "أنثى", age: "العمر", height: "الطول", weight: "الوزن",
        activity: "مستوى النشاط", act1: "خامل", act2: "نشاط خفيف", act3: "نشاط متوسط", act4: "شديد النشاط",
        mealMode: "🍽️ نظام الوجبات", mode4: "عادي (٣ وجبات + سناك)", mode3: "٣ وجبات", mode2: "وجبتين (صيام ١٦٨)", mode1: "وجبة واحدة",
        btnCalc: "🔄 حفظ وتحديث", resTdee: "إجمالي الحرق", resTarget: "الهدف",
        modalTitle: "تقرير الذكاء الاصطناعي", modalAsk: "لأي وجبة؟", btnCancel: "إلغاء",
        favTitle: "قائمة المفضلة", btnClose: "إغلاق",
        menuImport: "استيراد البيانات", menuExport: "تصدير البيانات", menuTheme: "تغيير المظهر", menuLang: "اللغة", suggest: "مُقترح",
        langTitle: "اللغة", langCancel: "إلغاء",
        meals: { breakfast: "🍳 فطور", lunch: "🍱 غداء", dinner: "🍲 عشاء", snack: "🍪 سناك", meal1: "🍽️ وجبة ١", meal2: "🍽️ وجبة ٢", mealBig: "🏆 الوجبة الكبيرة" },
        alertDel: "حذف هذا العنصر؟", alertFavAdded: "تم الحفظ في المفضلة!", alertFavExist: "موجود مسبقاً في المفضلة!", alertSelImg: "الرجاء اختيار صورة!", alertAiFail: "فشل تحليل الذكاء الاصطناعي: ", alertFill: "الرجاء ملء جميع الحقول", alertNameCal: "أدخل الاسم والسعرات", alertImportOk: "🎉 تمت الاستعادة بنجاح!", alertImportFail: "❌ تنسيق الملف غير صحيح",
        weightTitle: "⚖️ سجل الوزن", weightInputPlaceholder: "وزن اليوم (كجم)", btnSaveWeight: "حفظ", weightChartTitle: "📈 مسار الوزن (اخر ٣٠ يوم)", textAiLabel: "📝 أدخل ما أكلته أو أضف تفاصيل لتحسين دقة الذكاء الاصطناعي：", textAiPlaceholder: "مثال: مكرونة بالصلصة بدون لحم...", appSettingsTitle: "🔧 إعدادات التطبيق", navDaily: "يوميات", navDashboard: "لوحة القيادة", navAi: "الذكاء الاصطناعي", navSettings: "إعدادات", txtWeightSettingsTitle: "الوزن (كجم)", alertWeightSaved: "تم حفظ الوزن بنجاح!", alertInvalidWeight: "الرجاء إدخال وزن صحيح!", alertSelImgOrText: "الرجاء تحديد صورة أو إدخال نص!",
        petMsg1: "ووف... أنا جائع جداً... (0%)", petMsg2: "لدي القليل من الطاقة ولكن أريد المزيد...", petMsg3: "أشم الطعام! جاري البحث...", petMsg4: "تغذية ممتازة! عمل رائع!", petMsg5: "تجشؤ... أكلت كثيراً!", petEatMsg: "يم يم... لذيذ!", petInteractMsg1: "ووف! هل شربت الماء اليوم؟", petInteractMsg2: "لنبقى بصحة جيدة معاً!", petInteractMsg3: "أنا أحب الطعام الصحي!", petInteractMsg4: "لن تنحف بمداعبتي، اذهب للرياضة! XD", petInteractMsg5: "تذكر أن تمضغ ببطء!",
        macroGoalTitle: "📊 الماكروز المقترحة (تقدير):", txtTdeeUnit: " (إجمالي حرق الطاقة)", txtResTarget: "الوزن المستهدف",
        txtTargetCalDisplayUnit: "الهدف",
        phPro: "البروتين", phFat: "الدهون", phCarb: "الكربوهيدرات", phSugar: "السكر", phSod: "الصوديوم", phSat: "الدهون المشبعة", phTrans: "الدهون المتحولة",
        txtManualLabel: "إدخال يدوي", btnAddRecord: "إضافة للسجل", txtRecordTitle: "سجل الوجبات", 
        btnFavSave: "حفظ في المفضلة", btnFavLoad: "اختيار من المفضلة", phFoodName: "اسم الطعام (مطلوب)", phFoodCal: "السعرات (ك.ك) (مطلوب)",
        chartCalTrend: "📈 اتجاه السعرات الحرارية", chartProteinTrend: "💪 اتجاه البروتين", chart7d: "٧ أيام", chart30d: "٣٠ يوم", chartTdeeTarget: "خط هدف TDEE",
        fiber: "ألياف", healthScoreLabel: "🏅 درجة الصحة", aiItemsLabel: "📋 تقدير مكونات الطعام", itemName: "الطعام", itemWeight: "الوزن", addItem: "＋ إضافة عنصر", recalculate: "🔄 إعادة الحساب", unsavedWarning: "تنبيه: لم يتم حفظ بيانات التغذية. هل أنت متأكد من المغادرة؟",
        detailTitle: "📋 تفاصيل التغذية", noData: "--", btnDetailClose: "إغلاق"
    }
};
